### ISSUE TITLE
Impure Client Detected Error

### ISSUE THREAD

**Issue by EnGlamdring** [CoD4X/CoD4X18_client#3]
---
## Error

Impure client detected. Invalid .IWD files referenced!
C:\Program Files (x86)\Activision\Call of Duty 4 - Modern Warfare\main\iw_13.iwd

Any ideas?

**Comment by uGiFarukh** [comment]
Really sorry for any inconvenience. You can try to replace the cod4 main->*.iwd files with the original non modified copy of cod4 game. Hopefully that will fix this issue. Currently the project is not maintained and no support will be provided regarding any issue in the future.
